version: '3.9'
services:
  api:
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://openbanking:openbanking@postgres:5432/openbanking?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_ISSUER_SIGNING_KEY=insecure-development-secret
    volumes:
      - ./:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=openbanking
      - POSTGRES_PASSWORD=openbanking
      - POSTGRES_DB=openbanking
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U openbanking']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
volumes:
  postgres-data:
